# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rohanjp2/cs225git/rohanjp2-kdadi2-amart317

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rohanjp2/cs225git/rohanjp2-kdadi2-amart317

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rohanjp2/cs225git/rohanjp2-kdadi2-amart317/CMakeFiles /home/rohanjp2/cs225git/rohanjp2-kdadi2-amart317/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rohanjp2/cs225git/rohanjp2-kdadi2-amart317/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test-pokemon

# Build rule for target.
test-pokemon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-pokemon
.PHONY : test-pokemon

# fast build rule for target.
test-pokemon/fast:
	$(MAKE) $(MAKESILENT) -f pokemon_testing/CMakeFiles/test-pokemon.dir/build.make pokemon_testing/CMakeFiles/test-pokemon.dir/build
.PHONY : test-pokemon/fast

#=============================================================================
# Target rules for targets named main-pokemon

# Build rule for target.
main-pokemon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-pokemon
.PHONY : main-pokemon

# fast build rule for target.
main-pokemon/fast:
	$(MAKE) $(MAKESILENT) -f pokemon_testing/CMakeFiles/main-pokemon.dir/build.make pokemon_testing/CMakeFiles/main-pokemon.dir/build
.PHONY : main-pokemon/fast

#=============================================================================
# Target rules for targets named PokemonLib

# Build rule for target.
PokemonLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PokemonLib
.PHONY : PokemonLib

# fast build rule for target.
PokemonLib/fast:
	$(MAKE) $(MAKESILENT) -f pokemon_testing/CMakeFiles/PokemonLib.dir/build.make pokemon_testing/CMakeFiles/PokemonLib.dir/build
.PHONY : PokemonLib/fast

#=============================================================================
# Target rules for targets named test-graph

# Build rule for target.
test-graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-graph
.PHONY : test-graph

# fast build rule for target.
test-graph/fast:
	$(MAKE) $(MAKESILENT) -f graph_testing/CMakeFiles/test-graph.dir/build.make graph_testing/CMakeFiles/test-graph.dir/build
.PHONY : test-graph/fast

#=============================================================================
# Target rules for targets named main-graph

# Build rule for target.
main-graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-graph
.PHONY : main-graph

# fast build rule for target.
main-graph/fast:
	$(MAKE) $(MAKESILENT) -f graph_testing/CMakeFiles/main-graph.dir/build.make graph_testing/CMakeFiles/main-graph.dir/build
.PHONY : main-graph/fast

#=============================================================================
# Target rules for targets named GraphLib

# Build rule for target.
GraphLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GraphLib
.PHONY : GraphLib

# fast build rule for target.
GraphLib/fast:
	$(MAKE) $(MAKESILENT) -f graph_testing/CMakeFiles/GraphLib.dir/build.make graph_testing/CMakeFiles/GraphLib.dir/build
.PHONY : GraphLib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GraphLib"
	@echo "... PokemonLib"
	@echo "... main-graph"
	@echo "... main-pokemon"
	@echo "... test-graph"
	@echo "... test-pokemon"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

